name: Generate Breakout Preview

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Breakout SVGs
        uses: cyprieng/github-breakout@v1
        with:
          github_username: GanestGamer11

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Publish Breakout SVGs
        run: |
          git checkout --orphan github-breakout
          git rm -rf .
          mkdir -p images
          mv output/light.svg images/breakout-light.svg
          mv output/dark.svg images/breakout-dark.svg
          git add images
          git commit -m "chore: update breakout svg" || echo "No changes to commit"
          git push --force origin github-breakout
